defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build.prod
  unit_tests:
    <<: *defaults
    docker:
      - image: circleci/node:10.12-browsers
    # environment:
    #   TEST_REPORT_FILENAME: 'test-results.xml'
    #   TZ: '/usr/share/zoneinfo/America/Chicago'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci
      - run:
          name: Test
          command:
            npm test
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: ./coverage
      # - run:
      #     name: Post coverage results
      #     command:
      #       'node_modules/.bin/codecov --token=c3fb1296-98dd-4bc2-a4d1-8a23e4294278'
  # e2e_tests:
  #   <<: *defaults
  #   docker:
  #     - image: circleci/node:10.12-browsers
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install npm
  #         command: npm ci
  #     - run:
  #         name: Test
  #         command: 'npm run gen.config && CI_ENV=stag npm run test.e2e.ci'
  # semver:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install npm
  #         command: npm ci
  #     - run:
  #         name: Semantic Release
  #         command: ./node_modules/.bin/semantic-release
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install npm
  #         command: npm ci
  #     - run:
  #         name: Step1
  #         command: chmod +x ./aws_circle_ci_creds.sh
  #     - run:
  #         name: Step2
  #         command: ./aws_circle_ci_creds.sh
  #     - run:
  #         name: deploy
  #         command: npm run deploy -- --env-config int01
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - unit_tests
      # - e2e_tests
      # - semver:
      #     requires:
      #       - build
      #       - unit_tests
      #       - e2e_tests
      #     filters:
      #       branches:
      #         only: master
#   - deploy:
#       requires:
#         - build
#         - unit_tests
#         - e2e_tests
#         - lint
#         - bundlesize
#       filters:
#         branches:
#           only: develop
