defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12-browsers

version: 2
jobs:
  build_production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Exectue Lint
          command: npm run lint
      - run:
          name: Exectue Build
          command: npm run build.prod
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command:
            npm run test.ci.app
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command:
            node_modules/.bin/codecov -F docs_site
  test_viewport_grid:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command:
            npm run test.ci.viewport-grid
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command:
            node_modules/.bin/codecov -F viewport-grid
  e2e:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Execute Tests
          command: ./node_modules/.bin/ng e2e --prod --protractor-config=./e2e/protractor-ci.conf.js
  # semver:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install npm
  #         command: npm ci
  #     - run:
  #         name: Semantic Release
  #         command: ./node_modules/.bin/semantic-release
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: Install npm
  #         command: npm ci
  #     - run:
  #         name: Step1
  #         command: chmod +x ./aws_circle_ci_creds.sh
  #     - run:
  #         name: Step2
  #         command: ./aws_circle_ci_creds.sh
  #     - run:
  #         name: deploy
  #         command: npm run deploy -- --env-config int01
workflows:
  version: 2
  build_test_release:
    jobs:
      - build_production
      - test_docs_site
      - test_viewport_grid
      - e2e
      # - semver:
      #     requires:
      #       - build
      #       - unit_tests
      #       - e2e_tests
      #     filters:
      #       branches:
      #         only: master
#   - deploy:
#       requires:
#         - build
#         - unit_tests
#         - e2e_tests
#         - lint
#         - bundlesize
#       filters:
#         branches:
#           only: develop
