defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12-browsers

version: 2
jobs:
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Exectue Lint
          command: npm run lint
      - run:
          name: Exectue E2E
          command: ./node_modules/.bin/ng e2e --prod --protractor-config=./e2e/protractor-ci.conf.js
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.app
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command: node_modules/.bin/codecov -F docs_site
  test_viewport_grid:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.viewport-grid
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command: node_modules/.bin/codecov -F viewport_grid
  test_hls:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.hls
      - store_artifacts:
          path: coverage
      - run:
          name: Post coverage results
          command: node_modules/.bin/codecov -F hls
workflows:
  version: 2
  build_test_release:
    jobs:
      - test_docs_site
      - test_viewport_grid
      - test_hls
      - e2e
