defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:12.4-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Libraries
          command: npm run build.lib
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build.prod
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  prep_coverage:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https:/codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - persist_to_workspace:
          root: .
          paths:
            - cc-test-reporter
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Exectue E2E
          command: npm run e2e.ci
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test flo-angular -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.flo-angular.json ./coverage/flo-angular/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.flo-angular.json
  test_mse:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-media-source-extensions -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-media-source-extensions.json ./coverage/ng-media-source-extensions/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-media-source-extensions.json
  test_services:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-universal-services -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-universal-services.json ./coverage/ng-universal-services/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-universal-services.json
  test_icons:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-icons -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-icons.json ./coverage/ng-icons/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-icons.json
  test_styles:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-styles -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-styles.json ./coverage/ng-styles/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-styles.json
  test_svg-transfer-state:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-svg-transfer-state -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-svg-transfer-state.json ./coverage/ng-svg-transfer-state/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-svg-transfer-state.json
  test_env-transfer-state:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-env-transfer-state -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-env-transfer-state.json ./coverage/ng-env-transfer-state/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-env-transfer-state.json
  test_ad-block:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-ad-block -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-ad-block.json ./coverage/ng-ad-block/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-ad-block.json
  test_http-cache-tags:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-http-cache-tags -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-http-cache-tags.json ./coverage/ng-http-cache-tags/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-http-cache-tags.json
  test_ima:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-ima -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-ima.json ./coverage/ng-ima/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-ima.json
  test_tabs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-tabs -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-tabs.json ./coverage/ng-tabs/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-tabs.json
  test_video-autoplay:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-video-autoplay -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-video-autoplay.json ./coverage/ng-video-autoplay/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-video-autoplay.json
  test_video-events:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-video-events -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-video-events.json ./coverage/ng-video-events/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-video-events.json
  test_grid-list:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-grid-list -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-grid-list.json ./coverage/ng-grid-list/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-grid-list.json
  test_fullscreen:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-fullscreen -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-fullscreen.json ./coverage/ng-fullscreen/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-fullscreen.json
  test_video-player:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            npm run test @flosportsinc/ng-media-player -- --watch=false --progress=false --browsers=ChromeHeadlessCI
            ./cc-test-reporter format-coverage -t lcov -o ./cc.ng-media-player.json ./coverage/ng-media-player/lcov.info
      - persist_to_workspace:
          root: .
          paths:
            - cc.ng-media-player.json
  upload_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./cc-test-reporter sum-coverage ./cc.*.json -p 16 -o ./cc.total.json
            ./cc-test-reporter upload-coverage -i ./cc.total.json
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release

workflows:
  version: 2
  build:
    jobs:
      - prep_coverage
      - build
      - e2e:
          requires:
            - build
      - test_docs_site:
          requires:
            - build
            - prep_coverage
      - test_mse:
          requires:
            - build
            - prep_coverage
      - test_services:
          requires:
            - build
            - prep_coverage
      - test_icons:
          requires:
            - build
            - prep_coverage
      - test_styles:
          requires:
            - build
            - prep_coverage
      - test_svg-transfer-state:
          requires:
            - build
            - prep_coverage
      - test_env-transfer-state:
          requires:
            - build
            - prep_coverage
      - test_ad-block:
          requires:
            - build
            - prep_coverage
      - test_http-cache-tags:
          requires:
            - build
            - prep_coverage
      - test_ima:
          requires:
            - build
            - prep_coverage
      - test_tabs:
          requires:
            - build
            - prep_coverage
      - test_video-autoplay:
          requires:
            - build
            - prep_coverage
      - test_video-events:
          requires:
              - build
              - prep_coverage
      - test_grid-list:
          requires:
              - build
              - prep_coverage
      - test_fullscreen:
          requires:
              - build
              - prep_coverage
      - test_video-player:
          requires:
              - build
              - prep_coverage
      - upload_coverage:
          requires:
            - test_docs_site
            - test_mse
            - test_services
            - test_icons
            - test_styles
            - test_svg-transfer-state
            - test_env-transfer-state
            - test_ad-block
            - test_http-cache-tags
            - test_ima
            - test_tabs
            - test_video-autoplay
            - test_video-events
            - test_grid-list
            - test_fullscreen
            - test_video-player
      - publish:
          requires:
            - test_docs_site
            - test_mse
            - test_services
            - test_icons
            - test_styles
            - test_svg-transfer-state
            - test_env-transfer-state
            - test_ad-block
            - test_http-cache-tags
            - test_ima
            - test_tabs
            - test_video-autoplay
            - test_video-events
            - test_grid-list
            - test_fullscreen
            - test_video-player
            - upload_coverage
            - e2e
          filters:
            branches:
              only: master
