defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12-browsers

version: 2
jobs:
  prep_coverage:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  e2e:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Exectue Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build.prod
      - run:
          name: Exectue E2E
          command: npm run e2e.ci
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.app
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.flo-angular.json coverage/flo-angular/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.flo-angular.json
  test_viewport_grid:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.viewport-grid
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.ng-viewport-grid.json coverage/ng-viewport-grid/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.ng-viewport-grid.json
  test_mse:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.mse
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.ng-media-source-extensions.json coverage/ng-media-source-extensions/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.ng-media-source-extensions.json
  test_mse-dash:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.mse-dash
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.ng-media-source-extensions-dash.json coverage/ng-media-source-extensions-dash/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.ng-media-source-extensions-dash.json
  test_mse-hls:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.mse-hls
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.ng-media-source-extensions-hls.json coverage/ng-media-source-extensions-hls/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.ng-media-source-extensions-hls.json
  test_services:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            npm run test.ci.services
            /tmp/cc-test-reporter format-coverage -t lcov -o tmp/cc.ng-universal-services.json coverage/ng-universal-services/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.ng-universal-services.json
  upload_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            /tmp/cc-test-reporter sum-coverage /tmp/cc.*.json -p 6 -o /tmp/cc.total.json
            /tmp/cc-test-reporter upload-coverage -i /tmp/cc.total.json
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release

workflows:
  version: 2
  build:
    jobs:
      - prep_coverage
      - e2e
      - test_docs_site:
          requires:
            - prep_coverage
      - test_viewport_grid:
          requires:
            - prep_coverage
      - test_mse:
          requires:
            - prep_coverage
      - test_mse-dash:
          requires:
            - prep_coverage
      - test_mse-hls:
          requires:
            - prep_coverage
      - test_services:
          requires:
            - prep_coverage
      - upload_coverage:
          requires:
            - test_docs_site
            - test_viewport_grid
            - test_mse
            - test_mse-dash
            - test_mse-hls
            - test_services
      - publish:
          requires:
            - test_docs_site
            - test_viewport_grid
            - test_mse
            - test_mse-dash
            - test_mse-hls
            - test_services
            - upload_coverage
            - e2e
          filters:
            branches:
              only: master
