defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12-browsers

version: 2
jobs:
  e2e:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Exectue Lint
          command: npm run lint
      - run:
          name: Exectue E2E
          command: ./node_modules/.bin/ng e2e --prod --protractor-config=./e2e/protractor-ci.conf.js
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.app
      - store_artifacts:
          path: coverage
  test_viewport_grid:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.viewport-grid
      - store_artifacts:
          path: coverage
  test_hls:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.hls
      - store_artifacts:
          path: coverage
  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            ./cc-test-reporter format-coverage -t lcov -o coverage/cc.flo-angular.json coverage/flo-angular/lcov.info
            ./cc-test-reporter format-coverage -t lcov -o coverage/cc.ng-hls.json coverage/ng-hls/lcov.info
            ./cc-test-reporter format-coverage -t lcov -o coverage/cc.ng-viewport-grid.json coverage/ng-viewport-grid/lcov.info
            ./cc-test-reporter sum-coverage coverage/cc.*.json -p 3
            ./cc-test-reporter upload-coverage
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release --dry-run

workflows:
  version: 2
  build:
    jobs:
      - test_docs_site
      - test_viewport_grid
      - test_hls
      - e2e
      - coverage:
          requires:
            - test_docs_site
            - test_viewport_grid
            - test_hls
      - publish:
          requires:
            - test_docs_site
            - test_viewport_grid
            - test_hls
            - e2e
          filters:
            branches:
              only: master
