defaults: &defaults
  resource_class: xlarge
  docker:
    - image: circleci/node:10.12-browsers

version: 2
jobs:
  prep_coverage:
    <<: *defaults
    steps:
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  e2e:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Exectue Lint
          command: npm run lint
      - run:
          name: Exectue E2E
          command: ./node_modules/.bin/ng e2e --prod --protractor-config=./e2e/protractor-ci.conf.js
  test_docs_site:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: |
            ./tmp/cc-test-reporter format-coverage -t lcov -o cc.flo-angular.json coverage/flo-angular/lcov.info
      - persist_to_workspace:
          root: tmp
          paths:
            - cc.flo-angular.json
      - run: ls /tmp -lah
  test_viewport_grid:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.viewport-grid
      - store_artifacts:
          path: coverage
  test_hls:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Test
          command: npm run test.ci.hls
      - store_artifacts:
          path: coverage
  upload_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/cc.*.json -p 3 -o tmp/cc.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/cc.total.json
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm ci
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release --dry-run

workflows:
  version: 2
  build:
    jobs:
      - prep_coverage
      # - e2e
      - test_docs_site:
          requires:
            - prep_coverage
      # - test_viewport_grid:
      #     requires:
      #       - prep_coverage
      # - test_hls:
      #     requires:
      #       - prep_coverage
      # - upload_coverage:
      #     requires:
      #       - test_docs_site
      # - test_viewport_grid
      # - test_hls
      # - publish:
      #     requires:
      #       - test_docs_site
      #       - test_viewport_grid
      #       - test_hls
      #       - e2e
      #     filters:
      #       branches:
      #         only: master
