export const DEFAULT_FLO_GRID_LIST_DEFAULT_VIEWCOUNT = 1
export const DEFAULT_FLO_GRID_LIST_MIN_VIEWCOUNT = 1
export const DEFAULT_FLO_GRID_LIST_MAX_VIEWCOUNT = 25

export const DEFAULT_FLO_GRID_LIST_OVERLAY_ENABLED = true
export const DEFAULT_FLO_GRID_LIST_OVERLAY_START = true
export const DEFAULT_FLO_GRID_LIST_OVERLAY_FADEOUT = 3000
export const DEFAULT_FLO_GRID_LIST_OVERLAY_THROTTLE = 30
