export const SVG_LOADER = 'flo.svg.loader'
export const SVG_LOADER_HTTP_REQUEST = 'flo.svg.loader.http'
export const SVG_REQUEST_PATTERN = 'flo.svg.pattern'
export const SVG_REQUEST_PATTERN_BASE = 'flo.svg.svr.pattern.base'
export const SVG_TRANSFER_KEY = 'flo.svg.ts.key'
export const SVG_DIRECTIVE_DEFAULT_STYLES = 'flo.svg.dir.styles'
export const SVG_DIRECTIVE_PARENT_STYLE_KEYS = 'flo.svg.dir.parent-styles'
export const SVG_LOADER_ERROR_RETURN_OPERATOR = 'flo.svg.loader.err.operator'
